version: "3"
services:
  db:
      build: ../databases/pg
      restart: always
      ports:
        - "5432:5432"
      env_file:
        - "databases.env"
      networks:
        - micro-bakery
  authentication:
      build: ../authentication
      restart: always
      ports:
        - "7433:7433"
      expose:
        - "7433"
      env_file:
        - "authentication.env"
      depends_on:
        - "bakery"
        - "db"
      networks:
        - micro-bakery
  bakery:
      build: ./bakery
      restart: always
      ports:
        - "3200:3200"
      expose:
        - "3200"
      env_file:
        - "bakery.env"
      networks:
        - micro-bakery
networks:
  micro-bakery:
    driver: bridge
